In [1]:
import numpy as np


In [2]:
x = np.array([2006, 2007, 2008, 2009, 2010])
y = np.array([40, 56, 78, 80, 40])

In [3]:
y_sum = sum(y)
print ("Sum of y:",y_sum)

Sum of y: 294


In [4]:
x_median = 2008

print("x median:", x_median)

x_value = (x-x_median)
print (x_value)
x_sqr = sum(x_value**2)
print (x_sqr)

x median: 2008
[-2 -1  0  1  2]
10


In [5]:
xy = (x_value*y)
xy_sum = sum(x_value*y)
print(xy)

print(xy_sum)
n =len(x)
print (n)

[-80 -56   0  80  80]
24
5


In [6]:
a = y_sum/n
print (a)
b = xy_sum/x_sqr
print(b)
for i in range(len(x_value)):
    y_new = a + b * x_value[i]
    print(y_new)

58.8
2.4
54.0
56.4
58.8
61.199999999999996
63.599999999999994


In [7]:
print(x)
print(y)
print(xy)
print(x_value)
for i in range(len(x_value)):
    y_new = a + b * x_value[i]
    print(y_new)

[2006 2007 2008 2009 2010]
[40 56 78 80 40]
[-80 -56   0  80  80]
[-2 -1  0  1  2]
54.0
56.4
58.8
61.199999999999996
63.599999999999994
